from __future__ import annotations

import ipaddress
import json
import os
import time
import urllib.request
from typing import Any, Dict, Iterable, Optional

from ryu.base import app_manager
from ryu.controller import handler, ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, DEAD_DISPATCHER, MAIN_DISPATCHER
from ryu.lib import hub
from ryu.lib.packet import ethernet, ether_types, packet
from ryu.ofproto import ofproto_v1_3


class IntegratedAdaptiveCloudController(app_manager.RyuApp):
    """Ryu bridge for the integrated FastAPI policy plane.

    The FastAPI application remains the combined model brain. This Ryu app gives
    Mininet/Open vSwitch a real OpenFlow 1.3 controller that learns L2 paths and
    periodically installs block/quarantine rules generated by Component 4.
    """

    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.mac_to_port: Dict[int, Dict[str, int]] = {}
        self.datapaths: Dict[int, Any] = {}
        self.installed_rule_keys: set[str] = set()
        self.api_url = os.environ.get("ADAPTIVE_API_URL", "http://127.0.0.1:8080").rstrip("/")
        self.sync_interval = float(os.environ.get("ADAPTIVE_RULE_SYNC_INTERVAL", "5"))
        self.rule_thread = hub.spawn(self._sync_rules_loop)

    @handler.set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev: Any) -> None:
        datapath = ev.msg.datapath
        self.datapaths[datapath.id] = datapath
        parser = datapath.ofproto_parser
        match = parser.OFPMatch()
        actions = [parser.OFPActionOutput(datapath.ofproto.OFPP_CONTROLLER, datapath.ofproto.OFPCML_NO_BUFFER)]
        self._add_flow(datapath, priority=0, match=match, actions=actions)
        self.logger.info("Registered datapath %s and installed table-miss rule", datapath.id)

    @handler.set_ev_cls(ofp_event.EventOFPStateChange, [MAIN_DISPATCHER, DEAD_DISPATCHER])
    def state_change_handler(self, ev: Any) -> None:
        datapath = ev.datapath
        if ev.state == MAIN_DISPATCHER:
            self.datapaths[datapath.id] = datapath
        elif ev.state == DEAD_DISPATCHER:
            self.datapaths.pop(datapath.id, None)
            self.mac_to_port.pop(datapath.id, None)

    @handler.set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev: Any) -> None:
        msg = ev.msg
        datapath = msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        in_port = msg.match["in_port"]

        pkt = packet.Packet(msg.data)
        eth = pkt.get_protocols(ethernet.ethernet)[0]
        if eth.ethertype == ether_types.ETH_TYPE_LLDP:
            return

        dpid = datapath.id
        self.mac_to_port.setdefault(dpid, {})
        self.mac_to_port[dpid][eth.src] = in_port
        out_port = self.mac_to_port[dpid].get(eth.dst, ofproto.OFPP_FLOOD)
        actions = [parser.OFPActionOutput(out_port)]

        if out_port != ofproto.OFPP_FLOOD:
            match = parser.OFPMatch(in_port=in_port, eth_dst=eth.dst, eth_src=eth.src)
            self._add_flow(datapath, priority=10, match=match, actions=actions, idle_timeout=60)

        data = None if msg.buffer_id == ofproto.OFP_NO_BUFFER else msg.data
        out = parser.OFPPacketOut(
            datapath=datapath,
            buffer_id=msg.buffer_id,
            in_port=in_port,
            actions=actions,
            data=data,
        )
        datapath.send_msg(out)

    def _add_flow(
        self,
        datapath: Any,
        priority: int,
        match: Any,
        actions: Iterable[Any],
        idle_timeout: int = 0,
        hard_timeout: int = 0,
    ) -> None:
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser
        instructions = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS, list(actions))]
        mod = parser.OFPFlowMod(
            datapath=datapath,
            priority=priority,
            match=match,
            instructions=instructions,
            idle_timeout=idle_timeout,
            hard_timeout=hard_timeout,
        )
        datapath.send_msg(mod)

    def _sync_rules_loop(self) -> None:
        while True:
            try:
                rules = self._fetch_controller_rules()
                for datapath in list(self.datapaths.values()):
                    self._install_controller_rules(datapath, rules)
            except Exception as exc:
                self.logger.warning("Security rule sync failed: %s", exc)
            hub.sleep(self.sync_interval)

    def _get_json(self, path: str) -> dict:
        request = urllib.request.Request(f"{self.api_url}{path}")
        with urllib.request.urlopen(request, timeout=2.0) as response:
            return json.loads(response.read().decode("utf-8"))

    def _fetch_controller_rules(self) -> list[dict]:
        rules: list[dict] = []
        for flow in self._safe_rule_list("/api/v1/component-1/flows", "flow_rules"):
            converted = self._component1_flow_to_rule(flow)
            if converted:
                rules.append(converted)
        rules.extend(self._safe_rule_list("/api/v1/component-3/rules", "active_rules"))
        rules.extend(self._safe_rule_list("/api/v1/component-4/rules", "active_rules"))
        return rules

    def _safe_rule_list(self, path: str, key: str) -> list[dict]:
        try:
            payload = self._get_json(path)
            return list(payload.get(key) or [])
        except Exception as exc:
            self.logger.debug("Could not read %s from integrated API: %s", path, exc)
            return []

    def _install_controller_rules(self, datapath: Any, rules: list[dict]) -> None:
        parser = datapath.ofproto_parser
        for rule in rules:
            if not self._rule_targets_datapath(rule, datapath.id):
                continue
            match = self._build_match(parser, rule.get("match") or {})
            if match is None:
                continue
            actions = self._build_actions(datapath, rule)
            rule_key = f"{datapath.id}:{rule.get('id') or rule.get('name') or time.time()}"
            if rule_key in self.installed_rule_keys:
                continue
            priority = int(rule.get("priority") or 300)
            idle_timeout = int(rule.get("idle_timeout_sec") or 0)
            hard_timeout = int(rule.get("hard_timeout_sec") or 0)
            self._add_flow(datapath, priority=priority, match=match, actions=actions, idle_timeout=idle_timeout, hard_timeout=hard_timeout)
            self.installed_rule_keys.add(rule_key)
            self.logger.info("Installed integrated rule %s on datapath %s", rule.get("id") or rule.get("name"), datapath.id)

    def _component1_flow_to_rule(self, flow: dict) -> Optional[dict]:
        client_ip = flow.get("client_ip")
        backend_ip = flow.get("backend_ip")
        egress_port = flow.get("egress_port")
        if not client_ip or not backend_ip or not egress_port:
            return None
        ip_proto = int(flow.get("ip_proto") or 6)
        match = {
            "eth_type": ether_types.ETH_TYPE_IP,
            "ipv4_src": client_ip,
            "ip_proto": ip_proto,
        }
        if ip_proto == 6:
            match["tcp_src"] = int(flow.get("client_port") or 0)
            match["tcp_dst"] = int(flow.get("vip_port") or 8000)
        elif ip_proto == 17:
            match["udp_src"] = int(flow.get("client_port") or 0)
            match["udp_dst"] = int(flow.get("vip_port") or 8000)
        return {
            "id": flow.get("id"),
            "component": "component-1",
            "dpid": flow.get("dpid"),
            "priority": flow.get("priority") or 100,
            "idle_timeout_sec": flow.get("idle_timeout_sec") or 30,
            "hard_timeout_sec": flow.get("hard_timeout_sec") or 300,
            "match": {key: value for key, value in match.items() if value not in {None, 0}},
            "actions": [
                {"type": "SET_FIELD", "field": "ipv4_dst", "value": backend_ip},
                {"type": "OUTPUT", "port": int(egress_port)},
            ],
        }

    def _build_match(self, parser: Any, match_data: dict) -> Optional[Any]:
        fields: dict[str, Any] = {}
        allowed = {
            "eth_type",
            "ipv4_src",
            "ipv4_dst",
            "ip_proto",
            "tcp_src",
            "tcp_dst",
            "udp_src",
            "udp_dst",
        }
        for key in allowed:
            value = match_data.get(key)
            if value is not None:
                fields[key] = value
        if not fields:
            subject = self._rule_ip_subject({"match": match_data})
            if subject:
                fields = {"eth_type": ether_types.ETH_TYPE_IP, "ipv4_src": subject}
        if not fields:
            return None
        return parser.OFPMatch(**fields)

    def _build_actions(self, datapath: Any, rule: dict) -> list[Any]:
        action_name = str(rule.get("action", "")).lower()
        if action_name in {"block", "quarantine", "deny"}:
            return []
        parser = datapath.ofproto_parser
        ofproto = datapath.ofproto
        built: list[Any] = []
        for action in rule.get("actions") or []:
            action_type = str(action.get("type", "")).upper()
            if action_type == "DROP":
                return []
            if action_type == "SET_FIELD":
                field = action.get("field")
                value = action.get("value")
                if field and value is not None:
                    built.append(parser.OFPActionSetField(**{str(field): value}))
            if action_type == "OUTPUT":
                port_value = action.get("port")
                if str(port_value).upper() == "NORMAL":
                    port = getattr(ofproto, "OFPP_NORMAL", ofproto.OFPP_FLOOD)
                elif str(port_value).upper() == "FLOOD":
                    port = ofproto.OFPP_FLOOD
                else:
                    try:
                        port = int(port_value)
                    except (TypeError, ValueError):
                        continue
                built.append(parser.OFPActionOutput(port))
        return built

    @staticmethod
    def _rule_targets_datapath(rule: dict, dpid: int) -> bool:
        raw = rule.get("dpid") or rule.get("switch")
        if raw is None:
            return True
        text = str(raw).lower().strip()
        if text.startswith("s") and text[1:].isdigit():
            return int(text[1:]) == int(dpid)
        try:
            return int(text) == int(dpid)
        except ValueError:
            return True

    @staticmethod
    def _rule_ip_subject(rule: dict) -> Optional[str]:
        candidates = [
            rule.get("subject"),
            (rule.get("match") or {}).get("ipv4_src"),
            (rule.get("match") or {}).get("src_ip"),
        ]
        for candidate in candidates:
            if not candidate:
                continue
            try:
                ipaddress.ip_address(str(candidate))
                return str(candidate)
            except ValueError:
                continue
        return None
